apiVersion: v1
data:
  application.properties: |
    quarkus.profile = dev
    mta.endpoint = mta-openshift-mta.apps.cluster-vmlxj.dynamic.opentlc.com
    mta.port = 443
    mta.protocol = https
    mta_url = ${mta.protocol}://${mta.endpoint}
    quarkus.rest-client.mta_json.url = ${mta.protocol}://${mta.endpoint}:${mta.port}/hub
    quarkus.kubernetes-client.devservices.enabled = false
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mtaanalysis
    sonataflow.org/workflow-app: mtaanalysis
  name: mtaanalysis-props
  namespace: default
