name: Container Images

on:
  push:
    branches: [ "main" ]
env:
  
  WORKFLOW_ID: mta
  WORKFLOW_VERSION: 0.0.1
    
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.WORKFLOW_ID }}
        tags: ${{ github.sha }}
        containerfiles: |
          pipeline/Builder-Dockerfile
    # - name: Push To quay.io
    #   id: push-to-quay
    #   uses: redhat-actions/push-to-registry@v2
    #   with:
    #     image: ${{ steps.build-image.outputs.image }}
    #     tags: ${{ steps.build-image.outputs.tags }}
    #     registry: quay.io/rgolangh
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Print image url
    #   run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  generate-manifests:
    runs-on: quay.io/ricardozanini/sonataflow-tools:0.32.0-snapshot
    steps:
    - name: kn
      run: ls -la ;kn workflow gen-manifests --help
      
  
